version: "3.8"

services:
  web:
    image: nextapp
    build:
      context: . # Use the current directory
      dockerfile: Dockerfile
    command: sh -c "npm i && npm run dev"
    restart: always # Specify the Dockerfile
    ports:
      - "3000:3000" # Map port 3000
    volumes:
      - ./app:/nextapp/app
      - ./components:/nextapp/components
      - ./constants:/nextapp/constants
      - ./hooks:/nextapp/hooks
      - ./lib:/nextapp/lib
      - ./public:/nextapp/public
      - ./types:/nextapp/types # Bind mount the current directory to /nextapp in the container
    environment: pk_dev_a2dfePJpR38agCwN3onDSzLADWtRVRixe4m0gWxzd4ieEVEOmvCIrNYcYQT_26pC